[package]
name = "kestrel_driver"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description.workspace = true

[[bin]]
name = "kestrel"
path = "src/main.rs"

[dependencies]
kestrel_common = { path = "../kestrel_common" }
